### PR TITLE
Update for breaking changes in 1.73 dynamic_image extension

### PR DESCRIPTION
**Pull request by sdebionne**
Should fix boostorg/gil#510.

### CODE REVIEW

**Comment by sdebionne** [comment]
@apolukhin I will look into that. I use `dynamic_image` and `io` extensions in my project with similar code, but I don't see anything obviously wrong with this snippet. The `dynamic_image` extension test coverage is not ideal though. To be investigated.

**Comment by mloskot** [comment]
@sdebionne I have just posted a comment with a little analysis of the problem, here https://github.com/boostorg/gil/issues/510#issuecomment-664044111

**Comment by sdebionne** [comment]
@apolukhin This should be fixed in develop and hopefully will make it to 1.74.

**Comment by mloskot** [comment]
I've just merged the fix to GIL's master, so it's going to be released indeed.

**Pull request closed without merging**
